apiVersion: v1
kind: Service
metadata:
  name: app-metrics
  labels:
    app: custom-app
    metrics: enabled
spec:
  selector:
    app: custom-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
